import os
import sys
import re
sys.path.insert(0, '.')
from app.config import OUTPUTS_DIR
from datetime import datetime

os.makedirs(OUTPUTS_DIR, exist_ok=True)


def markdown_to_plain(text: str) -> str:
    """Convert markdown to plain text for PDF/DOCX."""
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'#{1,6}\s', '', text)
    text = re.sub(r'`(.*?)`', r'\1', text)
    text = re.sub(r'\[(.*?)\]\(.*?\)', r'\1', text)
    return text.strip()


def create_pdf(title: str, content: str, session_id: str) -> str:
    """
    Creates a PDF file from title and content.
    Returns file path.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.colors import HexColor

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{session_id[:8]}_{timestamp}.pdf"
    filepath = os.path.join(OUTPUTS_DIR, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontSize=20,
        textColor=HexColor('#1f77b4'),
        spaceAfter=20
    )
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=13,
        textColor=HexColor('#1a1a2e'),
        spaceAfter=8,
        spaceBefore=12
    )
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=16,
        spaceAfter=8
    )
    caption_style = ParagraphStyle(
        'Caption',
        parent=styles['Normal'],
        fontSize=9,
        textColor=HexColor('#888888'),
        spaceAfter=20
    )

    story = []

    # Title
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(
        "Generated by Agentic Research Assistant | " + datetime.now().strftime("%B %d, %Y"),
        caption_style
    ))
    story.append(Spacer(1, 0.2 * inch))

    # Content — split by lines and style headings vs body
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.1 * inch))
            continue

        plain = markdown_to_plain(line)
        if not plain:
            continue

        # Detect heading lines
        if line.startswith('#'):
            story.append(Paragraph(plain, heading_style))
        elif line.startswith('**') and line.endswith('**'):
            story.append(Paragraph(plain, heading_style))
        elif line.startswith('- ') or line.startswith('* '):
            story.append(Paragraph('• ' + plain[2:], body_style))
        else:
            try:
                story.append(Paragraph(plain, body_style))
            except:
                story.append(Paragraph(plain.encode('ascii', 'ignore').decode(), body_style))

    doc.build(story)
    print(f"[doc_gen] PDF created: {filepath}")
    return filepath


def create_docx(title: str, content: str, session_id: str) -> str:
    """
    Creates a DOCX Word file from title and content.
    Returns file path.
    """
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{session_id[:8]}_{timestamp}.docx"
    filepath = os.path.join(OUTPUTS_DIR, filename)

    doc = Document()

    # Title
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Caption
    cap = doc.add_paragraph("Generated by Agentic Research Assistant | " + datetime.now().strftime("%B %d, %Y"))
    cap.runs[0].font.size = Pt(9)
    cap.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)
    cap.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    # Content
    lines = content.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            continue

        plain = markdown_to_plain(line)
        if not plain:
            continue

        if line.startswith('# '):
            doc.add_heading(plain, level=1)
        elif line.startswith('## '):
            doc.add_heading(plain, level=2)
        elif line.startswith('### '):
            doc.add_heading(plain, level=3)
        elif line.startswith('- ') or line.startswith('* '):
            p = doc.add_paragraph(plain[2:], style='List Bullet')
        else:
            doc.add_paragraph(plain)

    doc.save(filepath)
    print(f"[doc_gen] DOCX created: {filepath}")
    return filepath